<?php
/**
 * ReadAdSetBidding
 *
 * PHP version 5
 *
 * @category Class
 * @package  Criteo\Marketing
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Criteo API Transition Swagger
 *
 * This is used to help Criteo clients transition from MAPI to Criteo API
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Criteo\Marketing\Model;

use \ArrayAccess;
use \Criteo\Marketing\ObjectSerializer;

/**
 * ReadAdSetBidding Class Doc Comment
 *
 * @category Class
 * @description ad set bidding read model
 * @package  Criteo\Marketing
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ReadAdSetBidding implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ReadAdSetBidding';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'bid_amount' => '\Criteo\Marketing\Model\NillableDecimal',
        'bid_strategy' => 'string',
        'cost_controller' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPIFormats = [
        'bid_amount' => null,
        'bid_strategy' => null,
        'cost_controller' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'bid_amount' => 'bidAmount',
        'bid_strategy' => 'bidStrategy',
        'cost_controller' => 'costController'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'bid_amount' => 'setBidAmount',
        'bid_strategy' => 'setBidStrategy',
        'cost_controller' => 'setCostController'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'bid_amount' => 'getBidAmount',
        'bid_strategy' => 'getBidStrategy',
        'cost_controller' => 'getCostController'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    const BID_STRATEGY_ACTIONS = 'actions';
    const BID_STRATEGY_CLICKS = 'clicks';
    const BID_STRATEGY_CONVERSIONS = 'conversions';
    const BID_STRATEGY_DISPLAYS = 'displays';
    const BID_STRATEGY_INSTALLS = 'installs';
    const BID_STRATEGY_REVENUE = 'revenue';
    const BID_STRATEGY_STORE_CONVERSIONS = 'storeConversions';
    const BID_STRATEGY_VALUE = 'value';
    const BID_STRATEGY_VIEWED_IMPRESSIONS = 'viewedImpressions';
    const BID_STRATEGY_VISITS = 'Visits';
    const BID_STRATEGY_COMPLETED_VIDEO_VIEWS = 'completedVideoViews';
    const COST_CONTROLLER_COS = 'COS';
    const COST_CONTROLLER_CPC = 'CPC';
    const COST_CONTROLLER_CPI = 'CPI';
    const COST_CONTROLLER_CPM = 'CPM';
    const COST_CONTROLLER_CPO = 'CPO';
    const COST_CONTROLLER_CPSV = 'CPSV';
    const COST_CONTROLLER_CPV = 'CPV';
    const COST_CONTROLLER_DAILY_BUDGET = 'dailyBudget';
    

    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getBidStrategyAllowableValues()
    {
        return [
            self::BID_STRATEGY_ACTIONS,
            self::BID_STRATEGY_CLICKS,
            self::BID_STRATEGY_CONVERSIONS,
            self::BID_STRATEGY_DISPLAYS,
            self::BID_STRATEGY_INSTALLS,
            self::BID_STRATEGY_REVENUE,
            self::BID_STRATEGY_STORE_CONVERSIONS,
            self::BID_STRATEGY_VALUE,
            self::BID_STRATEGY_VIEWED_IMPRESSIONS,
            self::BID_STRATEGY_VISITS,
            self::BID_STRATEGY_COMPLETED_VIDEO_VIEWS,
        ];
    }
    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getCostControllerAllowableValues()
    {
        return [
            self::COST_CONTROLLER_COS,
            self::COST_CONTROLLER_CPC,
            self::COST_CONTROLLER_CPI,
            self::COST_CONTROLLER_CPM,
            self::COST_CONTROLLER_CPO,
            self::COST_CONTROLLER_CPSV,
            self::COST_CONTROLLER_CPV,
            self::COST_CONTROLLER_DAILY_BUDGET,
        ];
    }
    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['bid_amount'] = isset($data['bid_amount']) ? $data['bid_amount'] : null;
        $this->container['bid_strategy'] = isset($data['bid_strategy']) ? $data['bid_strategy'] : null;
        $this->container['cost_controller'] = isset($data['cost_controller']) ? $data['cost_controller'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getBidStrategyAllowableValues();
        if (!is_null($this->container['bid_strategy']) && !in_array($this->container['bid_strategy'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'bid_strategy', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getCostControllerAllowableValues();
        if (!is_null($this->container['cost_controller']) && !in_array($this->container['cost_controller'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'cost_controller', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets bid_amount
     *
     * @return \Criteo\Marketing\Model\NillableDecimal|null
     */
    public function getBidAmount()
    {
        return $this->container['bid_amount'];
    }

    /**
     * Sets bid_amount
     *
     * @param \Criteo\Marketing\Model\NillableDecimal|null $bid_amount bid_amount
     *
     * @return $this
     */
    public function setBidAmount($bid_amount)
    {
        $this->container['bid_amount'] = $bid_amount;

        return $this;
    }

    /**
     * Gets bid_strategy
     *
     * @return string|null
     */
    public function getBidStrategy()
    {
        return $this->container['bid_strategy'];
    }

    /**
     * Sets bid_strategy
     *
     * @param string|null $bid_strategy The intended optimization for the Ad Set
     *
     * @return $this
     */
    public function setBidStrategy($bid_strategy)
    {
        $allowedValues = $this->getBidStrategyAllowableValues();
        if (!is_null($bid_strategy) && !in_array($bid_strategy, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'bid_strategy', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['bid_strategy'] = $bid_strategy;

        return $this;
    }

    /**
     * Gets cost_controller
     *
     * @return string|null
     */
    public function getCostController()
    {
        return $this->container['cost_controller'];
    }

    /**
     * Sets cost_controller
     *
     * @param string|null $cost_controller How is spend controlled
     *
     * @return $this
     */
    public function setCostController($cost_controller)
    {
        $allowedValues = $this->getCostControllerAllowableValues();
        if (!is_null($cost_controller) && !in_array($cost_controller, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'cost_controller', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['cost_controller'] = $cost_controller;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


